site_name: "My API Documentation"
site_url: "https://mbell195.github.io/OAS-to-Developer-Portal-Generator/"
repo_url: "https://github.com/mbell195/OAS-to-Developer-Portal-Generator"
repo_name: "OAS-to-Developer-Portal-Generator"
edit_uri: "blob/main/docs/"

theme:
  name: "material"
  palette:
    - scheme: default
      primary: "blue"
      accent: "blue"
    - scheme: slate
      primary: "blue"
      accent: "blue"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.annotation
    - search.suggest
    - search.highlight

nav:
  - 'API Reference': 'index.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables